config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # get 'lists', to: 'lists#index'
  # get 'lists/:id', to: 'lists#show', as: :list

  resources :lists, only: [:index, :show, :create, :destroy] do
    resources :items, only: [:create]
  end
  # delete 'items/:id', to: 'items#destroy', as: :item_delete
  resources :items, only: [:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  validates :name, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists, dependent: :destroy
  has_many :items, through: :lists, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    lists_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    @item = Item.new(item_params)
    @item.list = List.find(params[:list_id])
    if @item.save
      flash[:alert] = 'you added an item!'
      redirect_to @item.list
      # redirect_back(fallback_location: @list)
    else
      flash[:alert] = 'add an item failed'
      # redirect_to @item.list
      redirect_back(fallback_location: lists_path)
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to @item.list
  end

  private

  def item_params
    params.require(:item).permit(:name, :quantity, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]

  def index
    @lists = List.where("user_id = ?", current_user)
    @list = List.new
  end

  def show
    @item = Item.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      flash[:alert] = 'you added a list!'

      redirect_to partial: 'list', locals: { list: @list }

      # redirect_to lists_path
      # redirect_back(fallback_location: root_path)
    else
      flash[:alert] = 'add a list failed'
      # redirect_to lists_path
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@list) }
    end

    # redirect_to partial: 'list', locals: { list: @list }
    # render partial: 'list', locals: { list: @list }
    # redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:title, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopping List</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/lists/_delete_list.html.erb
<%= link_to 'delete', list_path(list), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger my-1' %>

app/views/lists/_form_list.html.erb
<div class="card card-body">
  <%= simple_form_for [list] do |f| %>
    <%= f.input :title %>
    <%= f.submit "Add a list", class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/lists/index.html.erb
<h2><%= current_user.name %>' lists</h2>

<ul>
  <%= turbo_stream_from @lists %>

    <% @lists.each do |list| %>
      <%= turbo_frame_tag dom_id(list) do %>
        <li>
          <%= link_to list.title.capitalize, list_path(list), method: :get %>
          <%= link_to 'delete', list_path(list), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger my-1' %>
        </li>
      <% end %>
    <% end %>

</ul>

<%= turbo_frame_tag dom_id(@list) do %>
  <%= render 'form_list', list: @list %>
<% end %>

app/views/lists/show.html.erb
<h2><%= @list.title.capitalize %></h2>

<ul>
  <% @list.items.each do |item| %>
    <li>
      <%= item.name.capitalize %>, <%= item.quantity %>
      <%= link_to 'delete', item_path(item), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger my-1' %>
    </li>
  <% end %>
</ul>

<h5>Add item to list:</h5>
<%= simple_form_for [@list, @item] do |f| %>
  <%= f.input :name %>
  <%= f.input :quantity %>
  <%= f.submit "Add item", class: "btn btn-secondary" %>
<% end %>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <h2>Hello, <%= current_user.name %>!</h2>
<% else %>
  <h2>Hello!</h2>
<% end %>

<ul>
  <% if user_signed_in? %>
    <li><%= link_to 'Your lists', lists_path %></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to 'Sign up', new_user_registration_path%></li>
    <li><%= link_to 'Log in', new_user_session_path %></li>
  <% end %>
</ul>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>